### PR TITLE
Parameter's name changed: include -> folders

### PR DESCRIPTION
**Pull request by kdorichev**

### CODE REVIEW

**Comment by jph00** [comment]
Sorry @kdorichev there's conflicts in the exported modules. @sgugger this might be an ongoing problem, since the cell numbers change now on each export that adds a cell.

@kdorichev can you re-export (run the last cell of pretty much any notebook) and push again - that should fix the conflict.

**Comment by sgugger** [comment]
I may be able to do without the cell numbers and avoid such conflicts. Will work on that on Monday.

**Comment by kdorichev** [comment]
@jph00 Jeremy, re-exported, as you advised. The output of the cells was cleaned.
Yet so many conflicting files. I hope I didn't introduce a mess and am willing to start over from a clean fork.

**Comment by jph00** [comment]
You seem to have removed all outputs - which is not what we want. If you just run `tools/run-after-git-clone` it should only remove some metadata. Note also that we can't merge anything with conflicts.

I'll close this PR so that you can start fresh, as you suggested. :)

**Pull request closed without merging**
