### PR TITLE
Minor fix in test_shuffled

### PR DESCRIPTION
**Pull request by slawekslex**
The test_shuffled function was checking if two sequences contain the same set of distinct elements, rather if one is a permutation of the other. This matters where duplicated elements exist, for example test_shuffled(“ab”, “abba”) used to pass and fails after the fix.

TEST PLAN:
- Run all the existing test in 00_test and 01c_dataloader
- Added one more test that demonstrates the changed behaviour

### CODE REVIEW

**Comment by slawekslex** [comment]
This is obviously a small thing and as much me trying out the PR flow as anything

**Comment by jph00** [comment]
This only works for sortable lists. Not all lists are sortable (e.g. lists with more than one element type often aren't). Perhaps just check the lengths are the same before checking the sets are the same?

**Comment by slawekslex** [comment]
How about Counter(a)==Counter(b).
Checking the len still fails for something like 'abb', 'aab'

**Comment by jph00** [comment]
Good idea!

**Pull request merged**
