### PR TITLE
Added creation of .fastai folder

### PR DESCRIPTION
**Pull request by muellerzr**
Current bug: running 04_data_external's _get_config() will not create the directory if it is not there to load in the yml. 

Fix: `if not config_path.exists(): os.mkdir(config_path)`

### CODE REVIEW

**Comment by muellerzr** [comment]
Fixed using the pathlib library instead as Jeremy suggested

**Comment by jph00** [comment]
You've got an extra cell here running nbstripout. Can you instead run tool/run-after-git-clone and remove that cell from the nb?

**Comment by muellerzr** [comment]
Sure thing. I think that was mostly because I was trying to run everything via colab (where we have no CLI) but I'm moving it onto my local machine to git push. Should be done shortly!

**Comment by muellerzr** [comment]
Let me know if that worked :)

**Comment by jph00** [comment]
Have a look at the "files changed" tab on this PR, and you'll see that there's a really big diff there, including colab metadata. You'll know it's worked when the only things that have changed are the lines of code you modified. :)

**Comment by muellerzr** [comment]
Looks like that fixed it, except now it's changing everything even though they are the same... odd...

**Comment by muellerzr** [comment]
I'm unsure why it's not keeping that bottom bit. If it's a problem (which I assume it is) I'll go run it on paperspace real quick and adjust it.

**Pull request closed without merging**
