### PR TITLE
Proposition for improving the usability of iterable datasets

### PR DESCRIPTION
**Pull request by tacchinotacchi**
**This PR is not ready for merging**

Since I'm using iterable datasets and I wanted to be able to use the same tools I could use with indexable datasets (like multiple pipelines for different fields thanks to TfmdList and DataSource), I tried adding the analogous classes `TfmdIterator` and `IterableDataSource`. I also gave small improvements to `DataLoader`.

I understand that this is not ready for merging, as I modified fundamental classes like `TfmdList` without thinking of the implications on the docs, only added one test for each new class, and I don't really know enough about the workings of the library to make such edits responsibly. However, do you think this is a good general direction for supporting iterable datasets more seamlessly?

### CODE REVIEW

**Comment by jph00** [comment]
Thanks for the draft PR! The most useful thing for us would be to see a "tutorial" notebook, like 10_pets_tutorial, showing a practical example of what this is best used for, and how to use it. That way, we can see whether this is functionality that we'd like to incorporate - if so, we can then discuss how to incorporate it. :)

**Comment by tacchinotacchi** [comment]
The main reason I think this code would be useful is to make it easier to train for datasets that have so many examples that it would be better not to store the full list of indexes (in my case, I'm working on https://github.com/deepmind/mathematics_dataset, which has more than 10e8 training examples). Another candidate could http://opus.nlpl.eu/OpenSubtitles-v2018.php, a massive parallel corpus of media subtitles, but neither of these are very popular datasets. By any chance, do you know any more popular, similar datasets?

**Comment by tacchinotacchi** [comment]
It seems that this type of datasets isn't as widespread as I thought. Atm, I can't find a good example of a popular dataset for which it would be useful to load it without having to make an indexable class. I also found some bugs in the iterable classes that I don't have time to debug, so I'm closing the PR for now. I'll open it again if I find a more compelling example of a dataset that needs this.

**Comment by jph00** [comment]
OK - many thanks for your time on this.

**Pull request closed without merging**
