### PR TITLE
Add new tests

### PR DESCRIPTION
**Pull request by amaarora**
This PR pretty much adds a `test_fail` for every `test_eq` because right now we don't test for failing tests. 

I believe, Important ones are to check that `test_fail` can fail. Also, added a `test_fail` for `test_fig_exists`. 

New tests all added for `test_close` and these failures have been carefully added such as: 
`test_fail(lambda: test_eq_type([1,2.],map(int,[1,2])))`

### CODE REVIEW

**Comment by jph00** [comment]
I think this is a little over-enthusiastic! ;) Try to use `test_eq` and `test_ne` instead of `test_fail`, once they're defined. And also put the negative tests in a separate cell with `#hide` at the top, since they don't really help the reader of docs understand the functions.

**Comment by jph00** [comment]
@amaarora just a little ping for your two open PRs with comments... :)

**Comment by amaarora** [comment]
My sincere apologies @Jeremy 
Will fix by tonight AEST (around 4am pacific) as per comments.

**Comment by amaarora** [comment]
> @amaarora just a little ping for your two open PRs with comments... :)

Done :)

**Comment by jph00** [comment]
Thanks! I've looked thru this list of tests and I don't feel they're adding something that we need at the moment. But still appreciate the effort :)

**Pull request closed without merging**
